name: Deploy new image to ECR
# TODO: Update ECS images too
# TODO: Run migration deploy if touch on /migrations
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: sa-east-1
  REPOSITORY: saturn/api
  ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push image to ECR repository
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$REGISTRY/$REPOSITORY:$IMAGE_TAG" .
          docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
